openapi: 3.0.3
info:
  title: Go Server API
  version: 1.0.0
servers:
  - url: /
paths:
  /:
    get:
      operationId: getRoot
      summary: Root endpoint
      responses:
        "200":
          description: Root response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RootResponse"
  /health:
    get:
      operationId: getHealth
      summary: Health check
      responses:
        "200":
          description: Health status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
components:
  schemas:
    RootResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    HealthResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
