apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/squishmeist/cicd.git
    targetRevision: main
    path: deployment/helm/server
    helm:
      releaseName: go-server
      valueFiles:
        - values-go-server.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
