apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-cert
  namespace: default
spec:
  secretName: server-tls
  duration: 2160h # 90d
  renewBefore: 360h
  commonName: app.example.com
  dnsNames:
    - app.example.com
  issuerRef:
    name: squishmeist-ca
    kind: ClusterIssuer
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - server auth
