apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-cert
  namespace: argocd
spec:
  secretName: argocd-server-tls
  duration: 2160h # 90d
  renewBefore: 360h
  commonName: argocd.squishmeist.com
  dnsNames:
    - argocd.squishmeist.com
  issuerRef:
    name: squishmeist-ca
    kind: ClusterIssuer
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - server auth
