{{- $fullname := include "server.fullname" . -}}
{{- $secretName := "" -}}
{{- if .Values.secret.enabled -}}
  {{- $secretName = default (printf "%s-tls" $fullname) .Values.secret.name -}}
{{- end -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
  {{ include "server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  {{ include "server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
  {{ include "server.selectorLabels" . | nindent 8 }}
          {{ if .Values.podLabels }}
            {{ toYaml .Values.podLabels | nindent 8 }}
          {{ end }}
    spec:
{{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | nindent 8 }}
{{- end }}
      containers:
        - name: {{ .Values.container.name | default "server" }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
          volumeMounts:
            - name: app-config
              mountPath: {{ .Values.appConfig.mountPath }}
              subPath: {{ .Values.appConfig.key }}
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
{{- if .Values.securityContext }}
{{ toYaml .Values.securityContext | nindent 12 }}
{{- end }}
{{- if .Values.container.resources }}
          resources:
{{ toYaml .Values.container.resources | nindent 10 }}
{{- end }}
      volumes:
        - name: app-config
          secret:
            secretName: {{ .Values.appConfig.name }}
            items:
              - key: {{ .Values.appConfig.key }}
                path: {{ .Values.appConfig.key }}
