{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "server.fullname" . }}-policy
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "server.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- if .Values.networkPolicy.allowSameNamespaceIngress }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
    {{- end }}
    {{- range $ns := .Values.networkPolicy.allowedIngressNamespaces }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $ns }}
    {{- end }}
    {{- range .Values.networkPolicy.extraIngressRules }}
{{ toYaml (list .) | indent 4 }}
    {{- end }}
  egress:
    {{- if .Values.networkPolicy.allowDnsEgress }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    {{- end }}
    {{- range $port := .Values.networkPolicy.allowInternetEgress }}
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: {{ $port }}
          protocol: TCP
    {{- end }}
    {{- if .Values.networkPolicy.allowNtpEgress }}
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 123
          protocol: UDP
    {{- end }}
    {{- range .Values.networkPolicy.extraEgressRules }}
{{ toYaml (list .) | indent 4 }}
    {{- end }}
{{- end }}
