apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blink-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/squishmeist/cicd.git
    targetRevision: main
    path: deployment/blink-server
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
