apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: squishmeist-ca
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ${EMAIL_ADDRESS}
    privateKeySecretRef:
      name: squishmeist-ca
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class: traefik
