# Redis Helm Values
# Deploy a single Redis instance for internal cluster use.

architecture: standalone

auth:
  enabled: true
  password: ""
  existingSecret: ""
  usePasswordFiles: true

master:
  persistence:
    enabled: true
    size: 1Gi
    storageClass: ""
  service:
    type: ClusterIP
