# Traefik Helm Values
# This configuration sets up Traefik for HTTP routing only
# TLS/SSL certificates will be handled separately by Certbot

# Enable the ingress class
ingressClass:
  enabled: true
  isDefaultClass: true

# Service configuration
service:
  type: LoadBalancer

# Ports configuration
ports:
  web:
    port: 80
    expose:
      default: true
    exposedPort: 80
  websecure:
    port: 443
    expose:
      default: true
    exposedPort: 443