# Build stage
FROM golang:1.25 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY main.go .
ENV CGO_ENABLED=0 GOOS=linux
RUN go build -o server main.go

# Run stage
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/server .
CMD ["./server"]
